from __future__ import annotations

import json
from dataclasses import asdict

from .model import DecisionTable


def generate_python(table: DecisionTable) -> str:
    """Generate a dependency-free Python module for a canonical decision table.

    The generated module embeds the normalized table data and exposes
    ``evaluate(facts, as_of=None)``. It intentionally mirrors DTAC's native
    matcher and hit-policy semantics so a reviewed table can be shipped into a
    Python runtime without requiring the DTAC package at execution time.
    """
    payload = json.dumps(asdict(table), sort_keys=True, separators=(",", ":"), default=str)
    return _PYTHON_TEMPLATE.replace("__DTAC_TABLE_JSON__", repr(payload)).lstrip()


_PYTHON_TEMPLATE = r'''
# Generated by Decision Tables as Code (dtac). Do not edit by hand.
from __future__ import annotations

import json
import re
from datetime import date, datetime

_TABLE = json.loads(__DTAC_TABLE_JSON__)
_OPERATOR_KEYS = {"eq", "ne", "in", "not_in", "gt", "gte", "lt", "lte", "between", "exists", "regex"}


def _coerce_date(value):
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    if isinstance(value, str):
        try:
            return date.fromisoformat(value)
        except ValueError as exc:
            raise ValueError(f"Invalid ISO date {value!r}; expected YYYY-MM-DD") from exc
    raise TypeError("as_of must be an ISO date string, date, or datetime")


def _operator_matches(operator, expected, value, present):
    if operator == "exists":
        return present is bool(expected)
    if not present:
        return False
    if operator == "eq":
        return value == expected
    if operator == "ne":
        return value != expected
    if operator == "in":
        return value in expected
    if operator == "not_in":
        return value not in expected
    if operator == "gt":
        return value > expected
    if operator == "gte":
        return value >= expected
    if operator == "lt":
        return value < expected
    if operator == "lte":
        return value <= expected
    if operator == "between":
        if not isinstance(expected, list) or len(expected) != 2:
            raise ValueError("between requires [minimum, maximum]")
        return expected[0] <= value <= expected[1]
    if operator == "regex":
        return re.fullmatch(str(expected), str(value)) is not None
    raise ValueError(f"Unsupported condition operator: {operator}")


def _condition_matches(condition, value, present=True):
    if condition == "*":
        return present
    if isinstance(condition, dict):
        unknown = set(condition) - _OPERATOR_KEYS
        if unknown:
            raise ValueError(f"Unsupported condition operators: {', '.join(sorted(unknown))}")
        return all(_operator_matches(op, expected, value, present) for op, expected in condition.items())
    if isinstance(condition, list):
        return value in condition
    return value == condition


def _rule_matches(rule, facts):
    for name, condition in rule.get("when", {}).items():
        present = name in facts
        if not _condition_matches(condition, facts.get(name), present):
            return False
    return True


def _rule_is_effective(rule, evaluation_date):
    effective_from = rule.get("effective_from")
    effective_to = rule.get("effective_to")
    if effective_from is None and effective_to is None:
        return True
    if evaluation_date is None:
        raise ValueError(
            f"Rule {rule['id']!r} has effective dates; pass an explicit as_of date for deterministic evaluation"
        )
    if effective_from is not None and evaluation_date < _coerce_date(effective_from):
        return False
    if effective_to is not None and evaluation_date > _coerce_date(effective_to):
        return False
    return True


def evaluate(facts, *, as_of=None):
    """Evaluate facts and return a portable result dictionary."""
    if not isinstance(facts, dict):
        raise TypeError("facts must be a dict")
    evaluation_date = _coerce_date(as_of) if as_of is not None else None
    ordered = sorted(
        enumerate(_TABLE["rules"]),
        key=lambda pair: (pair[1].get("priority") is None, pair[1].get("priority") or 0, pair[0]),
    )
    matches = [
        rule
        for _, rule in ordered
        if _rule_is_effective(rule, evaluation_date) and _rule_matches(rule, facts)
    ]

    hit_policy = _TABLE["hit_policy"]
    if hit_policy == "first":
        selected = matches[:1]
        outputs = dict(selected[0]["then"]) if selected else None
    elif hit_policy == "unique":
        if len(matches) > 1:
            ids = ", ".join(rule["id"] for rule in matches)
            raise ValueError(f"UNIQUE hit policy violated; matched rules: {ids}")
        selected = matches
        outputs = dict(selected[0]["then"]) if selected else None
    elif hit_policy == "collect":
        selected = matches
        outputs = [dict(rule["then"]) for rule in selected]
    else:
        raise ValueError(f"Unsupported hit policy: {hit_policy}")

    return {
        "table_id": _TABLE["id"],
        "matched_rule_ids": [rule["id"] for rule in selected],
        "outputs": outputs,
    }


TABLE_ID = _TABLE["id"]
TABLE_VERSION = _TABLE["version"]
'''
