from __future__ import annotations

import json
from dataclasses import asdict

from .model import DecisionTable


def generate_javascript(table: DecisionTable) -> str:
    """Generate a dependency-free ES module for a canonical decision table."""
    payload = json.dumps(asdict(table), sort_keys=True, separators=(",", ":"), default=str)
    return _JAVASCRIPT_TEMPLATE.replace("__DTAC_TABLE_JSON__", payload).lstrip()


_JAVASCRIPT_TEMPLATE = r'''
// Generated by Decision Tables as Code (dtac). Do not edit by hand.
const TABLE = __DTAC_TABLE_JSON__;
const OPERATOR_KEYS = new Set(["eq", "ne", "in", "not_in", "gt", "gte", "lt", "lte", "between", "exists", "regex"]);

function coerceDate(value) {
  if (value instanceof Date) {
    if (Number.isNaN(value.getTime())) throw new TypeError("Invalid Date value");
    return value.toISOString().slice(0, 10);
  }
  if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value)) {
    const date = new Date(`${value}T00:00:00Z`);
    if (!Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === value) return value;
  }
  throw new TypeError("as_of must be a YYYY-MM-DD string or Date");
}

function operatorMatches(operator, expected, value, present) {
  if (operator === "exists") return present === Boolean(expected);
  if (!present) return false;
  if (operator === "eq") return value === expected;
  if (operator === "ne") return value !== expected;
  if (operator === "in") return expected.includes(value);
  if (operator === "not_in") return !expected.includes(value);
  if (operator === "gt") return value > expected;
  if (operator === "gte") return value >= expected;
  if (operator === "lt") return value < expected;
  if (operator === "lte") return value <= expected;
  if (operator === "between") {
    if (!Array.isArray(expected) || expected.length !== 2) throw new Error("between requires [minimum, maximum]");
    return expected[0] <= value && value <= expected[1];
  }
  if (operator === "regex") return new RegExp(`^(?:${String(expected)})$`).test(String(value));
  throw new Error(`Unsupported condition operator: ${operator}`);
}

function conditionMatches(condition, value, present = true) {
  if (condition === "*") return present;
  if (condition && typeof condition === "object" && !Array.isArray(condition)) {
    const unknown = Object.keys(condition).filter((key) => !OPERATOR_KEYS.has(key)).sort();
    if (unknown.length) throw new Error(`Unsupported condition operators: ${unknown.join(", ")}`);
    return Object.entries(condition).every(([operator, expected]) => operatorMatches(operator, expected, value, present));
  }
  if (Array.isArray(condition)) return condition.includes(value);
  return value === condition;
}

function ruleMatches(rule, facts) {
  return Object.entries(rule.when || {}).every(([name, condition]) => {
    const present = Object.prototype.hasOwnProperty.call(facts, name);
    return conditionMatches(condition, facts[name], present);
  });
}

function ruleIsEffective(rule, evaluationDate) {
  const from = rule.effective_from;
  const to = rule.effective_to;
  if (from == null && to == null) return true;
  if (evaluationDate == null) {
    throw new Error(`Rule '${rule.id}' has effective dates; pass an explicit as_of date for deterministic evaluation`);
  }
  if (from != null && evaluationDate < coerceDate(from)) return false;
  if (to != null && evaluationDate > coerceDate(to)) return false;
  return true;
}

export function evaluate(facts, { as_of = null } = {}) {
  if (!facts || typeof facts !== "object" || Array.isArray(facts)) throw new TypeError("facts must be an object");
  const evaluationDate = as_of == null ? null : coerceDate(as_of);
  const ordered = TABLE.rules
    .map((rule, index) => ({ rule, index }))
    .sort((a, b) => {
      const ap = a.rule.priority;
      const bp = b.rule.priority;
      if (ap == null && bp != null) return 1;
      if (ap != null && bp == null) return -1;
      if (ap != null && bp != null && ap !== bp) return ap - bp;
      return a.index - b.index;
    })
    .map(({ rule }) => rule);

  const matches = ordered.filter((rule) => ruleIsEffective(rule, evaluationDate) && ruleMatches(rule, facts));
  let selected;
  let outputs;

  if (TABLE.hit_policy === "first") {
    selected = matches.slice(0, 1);
    outputs = selected.length ? { ...selected[0].then } : null;
  } else if (TABLE.hit_policy === "unique") {
    if (matches.length > 1) {
      throw new Error(`UNIQUE hit policy violated; matched rules: ${matches.map((rule) => rule.id).join(", ")}`);
    }
    selected = matches;
    outputs = selected.length ? { ...selected[0].then } : null;
  } else if (TABLE.hit_policy === "collect") {
    selected = matches;
    outputs = selected.map((rule) => ({ ...rule.then }));
  } else {
    throw new Error(`Unsupported hit policy: ${TABLE.hit_policy}`);
  }

  return {
    table_id: TABLE.id,
    matched_rule_ids: selected.map((rule) => rule.id),
    outputs,
  };
}

export const TABLE_ID = TABLE.id;
export const TABLE_VERSION = TABLE.version;
'''
