from __future__ import annotations

import json
import shutil
import subprocess

import pytest

from decision_tables_as_code.io import load_table
from decision_tables_as_code.runtime_js import generate_javascript


def test_javascript_generation_is_deterministic_and_dependency_free():
    table = load_table("examples/order-routing.yaml")
    first = generate_javascript(table)
    second = generate_javascript(table)

    assert first == second
    assert "Generated by Decision Tables as Code" in first
    assert "export function evaluate" in first
    assert "decision_tables_as_code" not in first
    assert "require(" not in first


def test_generated_javascript_matches_expected_route_when_node_available(tmp_path):
    node = shutil.which("node")
    if node is None:
        pytest.skip("Node.js is not installed in this test environment")

    module_path = tmp_path / "routing.mjs"
    module_path.write_text(generate_javascript(load_table("examples/order-routing.yaml")), encoding="utf-8")
    runner_path = tmp_path / "run.mjs"
    runner_path.write_text(
        "import { evaluate } from './routing.mjs';\n"
        "console.log(JSON.stringify(evaluate({country:'DE', customer_type:'B2B', order_value:6000})));\n",
        encoding="utf-8",
    )

    completed = subprocess.run(
        [node, str(runner_path)],
        check=True,
        capture_output=True,
        text=True,
        cwd=tmp_path,
    )
    result = json.loads(completed.stdout)
    assert result["matched_rule_ids"] == ["de-b2b-high"]
    assert result["outputs"]["route"] == "enterprise-desk"
