from __future__ import annotations

from decision_tables_as_code.engine import evaluate
from decision_tables_as_code.io import load_table
from decision_tables_as_code.runtime import generate_python


def _load_generated(source: str):
    namespace: dict[str, object] = {}
    exec(compile(source, "<generated-dtac>", "exec"), namespace)
    return namespace


def test_generated_python_matches_native_unique_evaluation():
    table = load_table("examples/order-routing.yaml")
    source = generate_python(table)
    generated = _load_generated(source)
    facts = {"country": "DE", "customer_type": "B2B", "order_value": 6000}

    native = evaluate(table, facts)
    portable = generated["evaluate"](facts)

    assert portable == {
        "table_id": native.table_id,
        "matched_rule_ids": list(native.matched_rule_ids),
        "outputs": native.outputs,
    }
    assert portable["matched_rule_ids"] == ["de-b2b-high"]
    assert portable["outputs"]["route"] == "enterprise-desk"


def test_generated_python_has_no_dtac_runtime_import():
    source = generate_python(load_table("examples/order-routing.yaml"))

    assert "decision_tables_as_code" not in source
    assert "import yaml" not in source
    assert "Generated by Decision Tables as Code" in source


def test_generated_python_preserves_effective_date_requirement():
    table = load_table("examples/effective-routing.yaml")
    generated = _load_generated(generate_python(table))

    before = generated["evaluate"]({"country": "DE"}, as_of="2026-12-31")
    after = generated["evaluate"]({"country": "DE"}, as_of="2027-01-01")

    assert before != after
